// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {sync} from '../models';
import {main} from '../models';

export function CleanServer():Promise<string>;

export function CreateAPIKey(arg1:string,arg2:string):Promise<void>;

export function DeleteAPIKey(arg1:string):Promise<void>;

export function DeleteBatchServerFiles(arg1:Array<string>):Promise<void>;

export function DeleteServerFile(arg1:string):Promise<void>;

export function ForceSyncBatchServerFiles(arg1:Array<string>):Promise<void>;

export function GetConfig():Promise<config.ClientConfig>;

export function GetJobs():Promise<Array<sync.SyncJob>>;

export function GetServerConfig():Promise<main.ServerConfigDTO>;

export function IsConfigured():Promise<boolean>;

export function ListAPIKeys():Promise<Array<main.APIKeyDTO>>;

export function ListClients():Promise<Array<main.ClientDTO>>;

export function ListServerFiles():Promise<Array<main.ServerFileInfo>>;

export function SaveConfig(arg1:config.ClientConfig):Promise<void>;

export function UpdateServerConfig(arg1:main.ServerConfigDTO):Promise<main.ServerConfigDTO>;
