// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CleanServer() {
  return window['go']['main']['App']['CleanServer']();
}

export function CreateAPIKey(arg1, arg2) {
  return window['go']['main']['App']['CreateAPIKey'](arg1, arg2);
}

export function DeleteAPIKey(arg1) {
  return window['go']['main']['App']['DeleteAPIKey'](arg1);
}

export function DeleteBatchServerFiles(arg1) {
  return window['go']['main']['App']['DeleteBatchServerFiles'](arg1);
}

export function DeleteServerFile(arg1) {
  return window['go']['main']['App']['DeleteServerFile'](arg1);
}

export function ForceSyncBatchServerFiles(arg1) {
  return window['go']['main']['App']['ForceSyncBatchServerFiles'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetJobs() {
  return window['go']['main']['App']['GetJobs']();
}

export function GetServerConfig() {
  return window['go']['main']['App']['GetServerConfig']();
}

export function IsConfigured() {
  return window['go']['main']['App']['IsConfigured']();
}

export function ListAPIKeys() {
  return window['go']['main']['App']['ListAPIKeys']();
}

export function ListClients() {
  return window['go']['main']['App']['ListClients']();
}

export function ListServerFiles() {
  return window['go']['main']['App']['ListServerFiles']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function UpdateServerConfig(arg1) {
  return window['go']['main']['App']['UpdateServerConfig'](arg1);
}
